services:
  healtriskhub:
    build: .
    container_name: healtriskhub-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    depends_on:
      - healtriskhub-db

  healtriskhub-db:
    image: postgres:15-alpine
    container_name: healtriskhub-db
    restart: always
    environment:
      POSTGRES_USER: hhub_admin
      POSTGRES_PASSWORD: Hhub333364
      POSTGRES_DB: HealtRiskHub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
