version: "3.8"  # แนะนำให้ใส่ version

services:
  healtriskhub:
    build: .
    container_name: healtriskhub-web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:3000
      DATABASE_URL: postgres://hhub_admin:Hhub333364@healtriskhub-db:5432/HealtRiskHub
        # ใช้ internal Docker DNS: healtriskhub-db
    depends_on:
      - healtriskhub-db
    networks:
      - network

  healtriskhub-db:
    image: postgres:15-alpine
    container_name: healtriskhub-db
    restart: always
    environment:
      POSTGRES_USER: hhub_admin
      POSTGRES_PASSWORD: Hhub333364
      POSTGRES_DB: HealtRiskHub
    ports:
      - "5432:5432"
    volumes:
      - healtriskhub_postgres_data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  healtriskhub_postgres_data:

networks:
  network:
    driver: bridge
